const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs');
function setup(handler){const store=new Map(),calls=[],events=[];const context=vm.createContext({window:{LIBRA_CONFIG:{useMock:false,apiBaseUrl:'https://localhost:7193/api'},dispatchEvent:e=>events.push(e.type)},sessionStorage:{getItem:k=>store.get(k),setItem:(k,v)=>store.set(k,v),removeItem:k=>store.delete(k)},setTimeout,clearTimeout,AbortController,URLSearchParams,Event,fetch:async(url,options)=>{calls.push({url,options,body:options.body?JSON.parse(options.body):null});const result=await handler(url,options);return {ok:result.status?result.status<400:true,status:result.status||200,json:async()=>result.body??{success:true,data:result.data}};}});vm.runInContext(fs.readFileSync('dist/api-live.js','utf8'),context);return {api:context.window.LibraAPI,calls,store,events};}
const rawBook={productId:1,title:'Sách',price:100000,stockQuantity:5,isActive:true,author:'Tác giả',category:'Văn học',publisher:'NXB',description:'Mô tả',isbn:'123',imageUrl:null};
test('Login unwraps data and sends JWT on later requests',async()=>{const {api,calls}=setup(async url=>({data:url.endsWith('/login')?{token:'jwt',userInfo:{customerId:7,fullName:'An',email:'a@b.vn',role:'Manager'}}:{customerId:7,fullName:'An',role:'Manager'}}));const user=await api.login({email:'a@b.vn',password:'secret'});assert.equal(user.role,'manager');await api.me();assert.equal(calls[1].options.headers.Authorization,'Bearer jwt');assert.equal(calls[0].options.credentials,undefined);});
test('Registration sends fullName and does not automatically sign in',async()=>{const {api,calls,store}=setup(async()=>({data:{customerId:8}}));await api.register({name:'An',email:'a@b.vn',password:'secret'});assert.equal(calls[0].body.fullName,'An');assert.equal(store.size,0);});
test('Catalog sends server search filters and pagination',async()=>{const {api,calls}=setup(async()=>({data:{items:[rawBook],page:2,totalPages:3,totalItems:20}}));const result=await api.catalog(new URLSearchParams('q=sach&category=Văn học&max=150000&page=2'));assert.equal(result.items[0].id,1);assert.equal(result.items[0].stock,5);assert.match(calls[0].url,/page=2/);assert.match(calls[0].url,/search=sach/);assert.equal(result.totalItems,20);});
test('Books fetches all pages without silently dropping products',async()=>{const {api,calls}=setup(async url=>({data:{items:[{...rawBook,productId:url.includes('page=1&')?1:2}],totalPages:2}}));assert.equal((await api.books()).length,2);assert.equal(calls.length,2);});
test('Cart mutations use backend cart item IDs',async()=>{const {api,calls}=setup(async()=>({data:{items:[]}}));await api.addCart(1,2);await api.changeCart(91,3);await api.removeCart(91);assert.equal(calls[0].body.productId,1);assert.match(calls[1].url,/Cart\/item\/91$/);assert.equal(calls[2].options.method,'DELETE');});
test('Product updates preserve metadata required by PUT',async()=>{const {api,calls}=setup(async()=>({data:rawBook}));await api.updateBook(1,{price:120000,stock:9});assert.equal(calls[1].body.title,'Sách');assert.equal(calls[1].body.stockQuantity,9);assert.equal(calls[1].body.isbn,'123');});
test('Checkout sends selected items and maps authoritative amounts',async()=>{const {api,calls}=setup(async()=>({data:{orderId:4,customerId:7,orderStatus:'PENDING_CONFIRMATION',subtotal:100000,shippingFee:30000,discountAmount:10000,totalAmount:120000,items:[{productId:1,productTitle:'Sách',unitPrice:100000,quantity:1}]}}));const result=await api.createOrder({addressId:2,items:[{productId:1,quantity:1}],discountCode:'GIAM10',paymentMethod:'COD'});assert.match(calls[0].url,/Orders\/checkout$/);assert.equal(calls[0].body.items.length,1);assert.equal(result.total,120000);assert.equal(result.status,'Chờ xác nhận');assert.equal(result.items[0].title,'Sách');});
test('Role and activation updates use separate backend endpoints',async()=>{const {api,calls}=setup(async()=>({data:{role:'Customer',isActive:true}}));await api.updateAccount(8,{role:'staff',active:false});assert.match(calls[1].url,/Users\/8\/role$/);assert.equal(calls[1].body.role,'Staff');assert.match(calls[2].url,/Users\/8\/status$/);assert.equal(calls[2].body.isActive,false);});
test('401 clears session and propagates expired-session event',async()=>{const {api,events}=setup(async()=>({status:401,body:{message:'Hết phiên'}}));await assert.rejects(api.request('/Cart'),/Hết phiên/);assert.equal(api.hasSession(),false);assert.deepEqual(events,['libra:unauthorized']);});
test('400 validation errors and 403 are surfaced',async()=>{const {api}=setup(async()=>({status:400,body:{errors:{AddressId:['Địa chỉ không hợp lệ']}}}));await assert.rejects(api.request('/Orders'),/Địa chỉ/);const other=setup(async()=>({status:403}));await assert.rejects(other.api.accounts(),/quyền/);});
test('Payment status reads do not mark an order paid',async()=>{const {api,calls}=setup(async()=>({data:{paymentStatus:'PENDING'}}));assert.equal((await api.paymentStatus(4)).paymentStatus,'PENDING');assert.equal(calls.length,1);assert.match(calls[0].url,/Payment\/status\/4$/);assert.equal(calls[0].options.method,undefined);});
test('Create book posts backend DTO and maps created product',async()=>{const {api,calls}=setup(async()=>({status:201,data:rawBook}));const result=await api.createBook({title:'Sách',price:100000,stockQuantity:5,isActive:true,author:'Tác giả',isbn:'123'});assert.match(calls[0].url,/\/Products$/);assert.equal(calls[0].options.method,'POST');assert.equal(calls[0].body.stockQuantity,5);assert.equal(calls[0].body.isActive,true);assert.equal(result.id,1);assert.equal(result.stock,5);});
test('Duplicate ISBN error is surfaced when creating book',async()=>{const {api}=setup(async()=>({status:400,body:{success:false,message:'Mã ISBN này đã tồn tại trong hệ thống.'}}));await assert.rejects(api.createBook({title:'Sách',isbn:'123'}),/ISBN/);});
